#NTLK DAY -1

## Exercise-1

In [0]:
import numpy as np

In [0]:
A = [[22,5,16,9], [13,20,19,0], [5,9,1,16], [27,13,15,19]]
B = [[10,5,20,20], [5,21,22,27], [26,19,22,3], [27,8,18,7]]
c = [24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20]
d = [3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6]

In [41]:
print('1. ', np.add(A,B))

1.  [[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]


In [42]:
print('2. ', np.subtract(A,B))

2.  [[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]


In [43]:
print('3. ', np.multiply(A,B))

3.  [[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]


In [48]:
print('4. ', np.dot(A,B))

4.  [[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]


In [52]:
print('5. ', np.add(c,d))

5.  [27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]


In [53]:
print('6. ', np.subtract(c,d))

6.  [ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]


In [55]:
print('7. ', np.multiply(c,d))

7.  [ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]


In [77]:
print('8. ', np.dot(c,d))

8.  2298


In [59]:
print('9. ', np.add(A,10))

9.  [[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]


In [60]:
print('10. ', np.add(B,10))

10.  [[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]


In [61]:
print('11. ', np.add(c,15))

11.  [39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]


In [62]:
print('12. ', np.add(d,15))

12.  [18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]


In [70]:
print('13. ', np.add(np.multiply(2,A), np.multiply(2,B)))

13.  [[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]


In [71]:
print('14. ', np.multiply(np.add(A,B),3))

14.  [[ 96  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]


In [73]:
print('15. ', np.multiply(np.add(np.subtract(np.add(np.subtract(A,B),A),B),B),4))

15.  [[ 136   20   48   -8]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]


## Exercise-2

# NTLK DAY -2